---
- name: prereqs
  ansible.builtin.apt:
    pkg:
    - git
  become: true

- name: Git checkout
  ansible.builtin.git:
    repo: '{{armbian_repo}}'
    dest: "{{source_dir}}"
    version: main
    depth: 1
    single_branch: yes
    update: false