---

- name: Copy start-wayland script
  ansible.builtin.copy:
    src: "{{item}}"
    dest: "/home/{{ansible_user}}/bin/"
    owner: "{{ansible_user}}"
    mode: '0744'
  loop:
  - kill-waydroid.sh
  - start-waydroid.sh