---

waydroid_dir: /var/lib/waydroid
waydroid_image_dir: "{{waydroid_dir}}/images"

cache_dir: "/home/{{ansible_user}}/.uni/proxy-cache/waydroid"
backup_dir: "{{cache_dir}}/backup"

images:
- system.img
- vendor.img

files:
- waydroid_base.prop
- waydroid.cfg
# - waydroid.log

backup_file: "/home/{{ansible_user}}/waydroid-init-{{ansible_architecture}}.tar.gz"

## Not used:
# system_url_x86: "https://sourceforge.net/projects/waydroid/files/images/system/lineage/waydroid_x86_64/lineage-18.1-20230422-VANILLA-waydroid_x86_64-system.zip/download"
# vendor_url_x86: "https://sourceforge.net/projects/waydroid/files/images/vendor/waydroid_x86_64/lineage-18.1-20230422-MAINLINE-waydroid_x86_64-vendor.zip/download"

# system_url_arm: "https://sourceforge.net/projects/waydroid/files/images/system/lineage/waydroid_arm64/lineage-18.1-20230422-VANILLA-waydroid_arm64-system.zip/download"
# vendor_url_arm: "https://sourceforge.net/projects/waydroid/files/images/vendor/waydroid_arm64/lineage-18.1-20230422-MAINLINE-waydroid_arm64-vendor.zip/download"
