---

- name: Does node have images?
  stat:
    path: "{{waydroid_image_dir}}/{{images [0]}}"
  register: image_on_node

- name: Set fact
  ansible.builtin.set_fact:
    node_has_images: "{{image_on_node.stat.exists}}"

- name: Does proxy cache exist?
  stat:
    path: "{{cache_dir}}/{{ansible_architecture}}/images/{{images [0]}}"
  register: proxy_cache
  delegate_to: localhost

- name: Set fact
  ansible.builtin.set_fact:
    proxy_cache_exists: "{{proxy_cache.stat.exists}}"

## Not used
# - name: Has node been initialized?
#   stat:
#     path: "{{waydroid_dir}}/{{files [0]}}"
#   register: file_on_node

